name: 'Static Index'
description: 'Makes a static index'
inputs:
  REPOSITORY:
    description: 'The name of the repository (org/name)'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub authentication token to use'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    REPOSITORY: ${{ inputs.REPOSITORY }}
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
