name: 'Static Index'
description: 'Makes a static index'
inputs:
  REPOSITORY_ID:
    description: 'Node ID of the repository'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub authentication token to use'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    REPOSITORY_ID: ${{ inputs.REPOSITORY_ID }}
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
