name: build

on:
  push: {}
  schedule:
  - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: ./.github/actions/build-index
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # REPOSITORY: "dept-of-make/oso"
          # REPOSITORY: "osohq/oso"
